### ISSUE TITLE
Add authentication for individual accounts (Blazor Identity)

### ISSUE THREAD

**Issue by hoeyi** [hoeyi/Ozym#252]
### Statement ###
As a user, I want to register, log in, and manage my account securely.

### Acceptance Criteria ###
Describe the conditions by which this requirement will be satisfied.
- [x] **New user creation;** Admin users may create new users.
    - Admins can register new accounts.
    - Users can log in with their credentials.
    - Users receive email confirmation for account activation. **(Postponed)**

- [x] **Account Management:** Users may self-serve for common account tasks.
    - Users can update their profile information.
    - Users can reset their passwords.
    - Users can log out securely.

- [ ] **(Optional) Security:** Users have options for securing access to their account.
    - Users can add multi-factor authentication using a TOTP authenticator **(Postponed)**

### Tasks ###
- [x] Define password policy.

**Comment by hoeyi** [comment]
### Postponed items
* Email confirmation and use. Docs use [SendGrid](https://sendgrid.com/) for implementing confirmation emails in lieu of trying to SMTP.
* Two-factor authentication requires additional work to set up and is low-priority.
